
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
       output:
        binder: rabbit
        content-type: application/json
server:
 port: 8084

